#!/usr/bin/env python3
"""Writes tests/entity_names.tsv: `name<TAB>character` rows, read by tests/entity_names_test.rs.

Sections: hand-written cases (descriptive names, block types), samples of the HTML5 entities (case-sensitive pairs like
Tilde ∼ / tilde ˜ included), then per Unicode block its first, middle and last named character, spelled with the
official Unicode name and in lowercase, then RANDOM_SAMPLES characters picked at random from the whole Unicode table.
Expected `a|b` means either. A name keeps its first meaning, so HTML entities win over lowercase Unicode
names (`tilde` is ˜, `TILDE` stays ~).
Run: python3 tests/entity_names_table.py"""
import html.entities
import random
import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BLOCKS_FILE = ROOT / "data/sources/Blocks.txt"
LATEX_FILE = ROOT / "data/entities/latex.wasp"
TABLE_FILE = ROOT / "tests/entity_names.tsv"
SAMPLES_PER_BLOCK = 3
RANDOM_SAMPLES = 1000
RANDOM_SEED = 2026  # a stable table: the same random characters every run
HTML_CASE_GROUP_STRIDE = 4  # every 4th group of entities differing only in case (Tilde, tilde)
HTML_OTHER_STRIDE = 20  # every 20th other entity
SKIPPED_BLOCKS = re.compile(r"Surrogates|Private Use|Variation Selectors|^Tags$")

# within one tag the words modify each other: `<:E with tilde below>` is one character, not E, with, tilde, below
HAND_WRITTEN_CASES = """\
Tilde	∼
tilde	˜|~
TILDE	~|˜
tilde tilde	≈
double tilde	≈
E with tilde below	Ḛ
arrow above tilde	⥴
arrow above bold tilde	⭌
alpha	α
infinity	∞
forall	∀
greek small letter alpha	α
fracture A	𝔄
double R	ℝ
upper 2	²
lower 2	₂
bold alpha	𝛂
bold italic alpha	𝜶
sans bold A	𝗔
ligature ae	æ
red circle	🔴
"""


def blocks():
	for line in BLOCKS_FILE.read_text().splitlines():
		match = re.match(r"([0-9A-F]+)\.\.([0-9A-F]+); (.+)", line)
		if match and not SKIPPED_BLOCKS.search(match[3]):
			yield match[3], int(match[1], 16), int(match[2], 16)


def named_characters(first, last):
	return [chr(code) for code in range(first, last + 1) if unicodedata.name(chr(code), "")]


def samples(characters):
	if len(characters) <= SAMPLES_PER_BLOCK:
		return characters
	step = (len(characters) - 1) / (SAMPLES_PER_BLOCK - 1)
	return [characters[round(i * step)] for i in range(SAMPLES_PER_BLOCK)]


def hand_written_rows():
	yield "# hand-written"
	yield from (tuple(line.split("\t")) for line in HAND_WRITTEN_CASES.splitlines())


def latex_entities():
	escaped = lambda value: re.sub(r"\\u\{([0-9a-fA-F]+)\}", lambda match: chr(int(match.group(1), 16)), value)
	return {name: escaped(value) for name, value in re.findall(r'^\t([^\s:]+): "((?:[^"\\]|\\.)*)"', LATEX_FILE.read_text(), re.M)}


def p198(name, value, latex):
	"""User decision P198: where HTML and LaTeX disagree, the LaTeX reading wins (asymp ≍, cdot ⋅), except for letters with
	a diacritic (ocirc ô), whose LaTeX readings latex.wasp keeps commented out"""
	return latex.get(name, value)


def html_rows():
	latex = latex_entities()
	entities = {name[:-1]: p198(name[:-1], value, latex) for name, value in html.entities.html5.items() if name.endswith(";")}
	case_groups = {}
	for name in entities:
		case_groups.setdefault(name.lower(), []).append(name)
	differing = [names for names in case_groups.values() if len({entities[name] for name in names}) > 1]
	others = [names[0] for names in case_groups.values() if names not in differing]
	yield "# HTML5 entities, differing only in case"
	yield from ((name, entities[name]) for names in differing[::HTML_CASE_GROUP_STRIDE] for name in names)
	yield "# HTML5 entities"
	yield from ((name, entities[name]) for name in others[::HTML_OTHER_STRIDE])


def block_rows():
	for block, first, last in blocks():
		characters = samples(named_characters(first, last))
		if characters:
			yield f"# {block}"
			for character in characters:
				yield unicodedata.name(character), character
				yield unicodedata.name(character).lower(), character


def random_rows():
	named = [character for _, first, last in blocks() for character in named_characters(first, last)]
	yield f"# {RANDOM_SAMPLES} random characters"
	for character in sorted(random.Random(RANDOM_SEED).sample(named, RANDOM_SAMPLES)):
		yield unicodedata.name(character), character


def table_lines(rows):
	"""Comments stay, a name already given is skipped: its first meaning wins."""
	given = set()
	for row in rows:
		if isinstance(row, str):
			yield row
		elif row[0] not in given:
			given.add(row[0])
			yield "\t".join(row)


def main():
	header = f"# entity name<TAB>expected character, generated by tests/entity_names_table.py (Unicode {unicodedata.unidata_version})"
	rows = [*hand_written_rows(), *html_rows(), *block_rows(), *random_rows()]
	TABLE_FILE.write_text("\n".join([header, *table_lines(rows)]) + "\n")
	print(f"wrote {TABLE_FILE}")


if __name__ == "__main__":
	main()
