#!/usr/bin/env python3
"""Writes tests/entity_names.tsv: `name<TAB>character` rows, read by tests/entity_names_test.rs.

The hand-written cases come first (case-sensitive and descriptive names), then per Unicode block a few samples
(first, middle and last named character) spelled with their official Unicode name.
Run: python3 probes/entity_names_table.py"""
import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BLOCKS_FILE = ROOT / "data/sources/Blocks.txt"
TABLE_FILE = ROOT / "tests/entity_names.tsv"
SAMPLES_PER_BLOCK = 3
SKIPPED_BLOCKS = re.compile(r"Surrogates|Private Use|Variation Selectors|^Tags$")

# within one tag the words modify each other: `<:E with tilde below>` is one character, not E, with, tilde, below
HAND_WRITTEN_CASES = """\
Tilde	∼
tilde	˜
TILDE	~
tilde tilde	≈
double tilde	≈
E with tilde below	Ḛ
arrow above tilde	⥴
arrow above bold tilde	⭌
"""


def blocks():
	for line in BLOCKS_FILE.read_text().splitlines():
		match = re.match(r"([0-9A-F]+)\.\.([0-9A-F]+); (.+)", line)
		if match and not SKIPPED_BLOCKS.search(match[3]):
			yield match[3], int(match[1], 16), int(match[2], 16)


def named_characters(first, last):
	return [chr(code) for code in range(first, last + 1) if unicodedata.name(chr(code), "")]


def samples(characters):
	if len(characters) <= SAMPLES_PER_BLOCK:
		return characters
	step = (len(characters) - 1) / (SAMPLES_PER_BLOCK - 1)
	return [characters[round(i * step)] for i in range(SAMPLES_PER_BLOCK)]


def block_rows():
	for block, first, last in blocks():
		characters = samples(named_characters(first, last))
		if characters:
			yield f"# {block}"
			yield from (f"{unicodedata.name(character)}\t{character}" for character in characters)


def main():
	header = f"# entity name<TAB>expected character, generated by probes/entity_names_table.py (Unicode {unicodedata.unidata_version})"
	TABLE_FILE.write_text("\n".join([header, "# hand-written", HAND_WRITTEN_CASES.rstrip(), *block_rows()]) + "\n")
	print(f"wrote {TABLE_FILE}")


if __name__ == "__main__":
	main()
