#!/usr/bin/env python3
"""The pinyin readings of the chinese block (<:chinese de> 的), in priority order: the seed's first character of a reading wins.

    python3 data/chinese_readings.py    # → data/sources/chinese_readings.tsv, data/sources/unihan_readings.tsv

1. chinese_readings.tsv: the character and pinyin columns of uruk_egypt's dicts/chinese.freq.tsv (4340 characters,
   by frequency rank; its other columns are personal and stay out of this repo). Readings marked `*` are personal notes;
   tone marks become numbers (háng → hang2), stray marks go (ben3: → ben3), and only Mandarin syllables stay.
2. unihan_readings.tsv: every CJK unified ideograph with a Mandarin reading in Unicode's Unihan database
   (https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip, Unihan_Readings.txt): kMandarin, the customary
   reading, first, then kHanyuPinlu (by its frequency counts), kTGHZ2013 and kXHC1983, the modern dictionaries;
   kHanyuPinyin only for a character without any of these. Characters by frequency: kHanyuPinlu's counts, kGradeLevel,
   the 2013 standard table (kTGHZ2013), then code point.
"""
import re
import unicodedata
import urllib.request
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
FREQUENCY_LIST = Path.home() / "Documents" / "uruk_egypt.nosync" / "dicts" / "chinese.freq.tsv"
FREQUENT_OUTPUT = HERE / "sources" / "chinese_readings.tsv"
UNIHAN_OUTPUT = HERE / "sources" / "unihan_readings.tsv"
UNIHAN_URL = "https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip"
UNIHAN_CACHE = HERE.parent / "probes" / "unihan" / "Unihan.zip"
READING_FIELDS = ["kMandarin", "kHanyuPinlu", "kTGHZ2013", "kXHC1983"]
FALLBACK_FIELD = "kHanyuPinyin"
TONE_MARKS = {"̄": "1", "́": "2", "̌": "3", "̀": "4"}
PERSONAL_NOTE = "*"
SYLLABLE = re.compile(r"[a-zü]+")


def numbered(reading):
	"""lǜ → lv4, háng → hang2, ben3: → ben3: a reading with its tone as a number"""
	decomposed = unicodedata.normalize("NFD", reading.lower().replace("u:", "ü"))
	tones = [TONE_MARKS[c] for c in decomposed if c in TONE_MARKS]
	letters = unicodedata.normalize("NFC", "".join(c for c in decomposed if c not in TONE_MARKS))
	syllable = SYLLABLE.search(letters)
	tone = tones[0] if tones else "".join(re.findall(r"[1-5]", letters[syllable.end():] if syllable else ""))[:1]
	return syllable.group(0).replace("ü", "v") + tone if syllable else ""


def unique(items):
	return list(dict.fromkeys(item for item in items if item))


def unihan_fields():
	"""code point → field → value"""
	if not UNIHAN_CACHE.exists():
		UNIHAN_CACHE.parent.mkdir(parents=True, exist_ok=True)
		urllib.request.urlretrieve(UNIHAN_URL, UNIHAN_CACHE)
	fields = {}
	with zipfile.ZipFile(UNIHAN_CACHE) as archive:
		texts = [archive.read(name).decode() for name in ("Unihan_Readings.txt", "Unihan_DictionaryLikeData.txt", "Unihan_OtherMappings.txt")]
	for line in (line for text in texts for line in text.splitlines() if line.startswith("U+")):
		code, field, value = line.split("\t", 2)
		fields.setdefault(int(code[2:], 16), {})[field] = value
	return fields, re.search(r"Unicode Version ([\d.]+)", texts[0]).group(1)


def field_readings(field, value):
	"""kHanyuPinlu de(5096) dé(1496) by count, kHanyuPinyin/kXHC1983/kTGHZ2013 location:reading,reading"""
	if field == "kHanyuPinlu":
		counted = re.findall(r"(\S+?)\((\d+)\)", value)
		return [reading for reading, _ in sorted(counted, key=lambda pair: -int(pair[1]))]
	if field in ("kHanyuPinyin", "kXHC1983", "kTGHZ2013"):
		return [reading for entry in value.split() for reading in entry.split(":")[-1].split(",")]
	return value.split()


def pinlu_count(value):
	return sum(int(count) for count in re.findall(r"\((\d+)\)", value or ""))


def unihan_readings():
	fields, version = unihan_fields()
	rows = []
	for code, character_fields in fields.items():
		readings = unique(numbered(r) for field in READING_FIELDS if field in character_fields for r in field_readings(field, character_fields[field]))
		readings = readings or unique(numbered(r) for r in field_readings(FALLBACK_FIELD, character_fields.get(FALLBACK_FIELD, "")))
		if readings:
			grade = int(character_fields.get("kGradeLevel", 99))
			order = (-pinlu_count(character_fields.get("kHanyuPinlu")), grade, "kTGHZ2013" not in character_fields, code)
			rows.append((order, chr(code), readings))
	rows.sort()
	header = f"# character\treadings (pinyin with tone numbers, / between readings), most frequent character first; from Unihan {version} (Unihan.zip, {UNIHAN_URL}): kMandarin, kHanyuPinlu, kTGHZ2013, kXHC1983, else kHanyuPinyin; generated by data/chinese_readings.py\n"
	UNIHAN_OUTPUT.write_text(header + "".join(f"{character}\t{'/'.join(readings)}\n" for _, character, readings in rows))
	return len(rows)


def frequent_readings(syllables):
	"""rank, character, readings of the frequency list; a character listed twice keeps its first rank and all readings"""
	merged = {}
	for line in FREQUENCY_LIST.read_text().splitlines():
		columns = line.split("\t")
		character = (columns[1].split() or [""])[0] if len(columns) > 3 else ""  # 冷 (!): a note after the character
		if not columns[0].strip().isdigit() or len(character) != 1:
			continue
		readings = [numbered(r) for r in re.split(r"[/,\s]+", columns[3]) if r and not r.startswith(PERSONAL_NOTE)]
		readings = [mandarin(r, syllables) for r in readings if mandarin(r, syllables)]
		rank, previous = merged.get(character, (int(columns[0]), []))
		merged[character] = (rank, unique(previous + readings))
	ordered = sorted(merged.items(), key=lambda item: item[1][0])
	header = "# character\treadings (pinyin with tone numbers, / between readings), most frequent character first; from the uruk_egypt chinese.freq.tsv\n"
	FREQUENT_OUTPUT.write_text(header + "".join(f"{character}\t{'/'.join(readings)}\n" for character, (_, readings) in ordered if readings))
	return len(ordered)


def mandarin(reading, syllables):
	"""the reading if a Mandarin syllable, lue4 spelled lve4 like Unihan's lüè, else nothing (personal spellings)"""
	for spelling in (reading, reading.replace("u", "v")):
		if spelling.rstrip("12345") in syllables:
			return spelling
	return ""


def mandarin_syllables():
	return {reading.rstrip("12345") for line in UNIHAN_OUTPUT.read_text().splitlines()[1:] for reading in line.split("\t")[1].split("/")}


if __name__ == "__main__":
	print(unihan_readings(), "Unihan characters →", UNIHAN_OUTPUT)
	print(frequent_readings(mandarin_syllables()), "frequent characters →", FREQUENT_OUTPUT)
